BloodFinder/Models/Blood.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace BloodFinder.Models
{
    public class Blood
    {

        public string UserId { get; set; }

        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter your address")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Please enter your phonenumber")]
        public string Phone_Number { get; set; }

        [Required(ErrorMessage = "Please select your bloodgroup")]
        public string BloodGroup { get; set; }

        [Required(ErrorMessage = "Please enter your email")]
        public string Email { get; set; }

        [Required]
        public string Message { get; set; }

        public byte[] file { get; set; }





    }
   
}

BloodFinder/Controllers/BloodController.cs
using BloodFinder.Models;
using BloodFinder.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BloodFinder.Controllers
{
    public class BloodController : Controller
    {

        [HttpGet] //DonateBlood
        public ActionResult DonateBlood()
        {

            ViewBag.Message = "Donate Blood, Save life";
            var ITEMlIST = new List<string>();
            ITEMlIST.Add("A positive");
            ITEMlIST.Add("O positive");
            ITEMlIST.Add("B positive");
            ITEMlIST.Add("AB positive");
            ITEMlIST.Add("A negative");
            ITEMlIST.Add("o negative");
            ITEMlIST.Add("B negative");
            ITEMlIST.Add("AB negative");


            ViewBag.BloodDonarList = ITEMlIST;

            return View();
        }

        [HttpPost] //DonateBlood
        public ActionResult DonateBlood(Blood b)
        {
            var loginId = Session["LoginId"].ToString();
            var dservice = new BloodService();
            var response = dservice.SaveBloodDonorData(b, loginId);
            ViewBag.Status = "Data successfully entered";
            return RedirectToActionPermanent("LastDonorList", "BloodList");
        }


        [HttpGet] //RequestBlood
        public ActionResult RequestforBlood()
        {
            ViewBag.Message = "Request Blood, Save your Life";
            var ITEMlIST = new List<string>();
            ITEMlIST.Add("A positive");
            ITEMlIST.Add("O positive");
            ITEMlIST.Add("B positive");
            ITEMlIST.Add("AB positive");
            ITEMlIST.Add("A negative");
            ITEMlIST.Add("o negative");
            ITEMlIST.Add("B negative");
            ITEMlIST.Add("AB negative");


            ViewBag.BloodLists = ITEMlIST;
            return View();
        }

        [HttpPost] //Request Blood
        public ActionResult RequestforBlood(Blood r)
        {
           
                var loginId = Session["LoginId"].ToString();
                var rservice = new BloodService();
                var response = rservice.SaveBloodRequestData(r, loginId);
            return RedirectToAction("SelfBloodRequestedList", "BloodList");


        }
    }
}

BloodFinder/Views/Blood/DonateBlood.cshtml
@model BloodFinder.Models.Blood



<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

<br /><br />
<style type="text/css">
    .label {
        font-weight: bold
    }
</style>


<div class="container-fluid">
    <div class="row">


        <br />
        <div class="col-lg-2">
            <img src="~/Photos/logo.png" alt="logo" height="100" width="100" />
        </div>

        <div class="col-lg-10">
            <div class="container">

                <h2><b>@ViewBag.Message</b></h2>

                @using (Html.BeginForm("DonateBlood", "Blood", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10 text-success">
                            @ViewBag.Status
                        </div>
                    </div>

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <label><b>Enter Name:</b></label>
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m=>m.Name, "", new { @class = "text-danger" })

                    </div>

                    <div class="form-group">
                        <label><b>Enter Address:</b></label>
                        @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Address, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label><b>Enter E-mail:</b></label>
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                    </div>

                    <div class="form-group">
                        <label><b>Enter Phone Number:</b></label>
                        @Html.TextBoxFor(m => m.Phone_Number, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Phone_Number, "", new { @class = "text-danger" })
                    </div>

                    @*<div class="form-group">
                        <label for="file"><b>Upload Image:</b></label><br />
                        <input type="file" name="file" id="file" /><br><br>
                        
                    </div>*@

                    <div class="form-group">
                        <label><b>Enter Blood Group:</b></label>
                        <br />
                        @Html.DropDownListFor(m => m.BloodGroup, new SelectList(ViewBag.BloodDonarList), "* Select Blood Group *")
                    </div>

                    <br />
                    <button type="submit" class="btn btn-success"><b>Save</b></button>

                    <button type="reset" class="btn btn-danger"><b>Cancel</b></button>

                }

            </div>
        </div>
    </div>
</div>

BloodFinder/Views/Blood/RequestforBlood.cshtml
@model BloodFinder.Models.Blood

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<br /><br />
<div class="container-fluid">
    <div class="row">
        <br />
        <div class="col-lg-2">
            <img src="~/Photos/logo.png" alt="logo" height="100" width="100" />
        </div>
        <div class="col-lg-10">

            <div class="container">
                <h2><b>@ViewBag.Message</b></h2>
                @using (Html.BeginForm("RequestforBlood", "Blood", FormMethod.Post))
                {
                    <div class="form-group">
                        <label><b>Enter Name:</b></label>
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })

                    </div>



                    <div class="form-group">
                        <label><b>Enter Address:</b></label>
                        @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label><b>Enter Phone Number:</b></label>
                        @Html.TextBoxFor(m => m.Phone_Number, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <label><b>Enter E-Mail:</b></label>
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label><b>Enter Blood Group:</b></label>
                        <br />
                        @Html.DropDownListFor(m => m.BloodGroup, new SelectList(ViewBag.BloodLists), "* Select Blood Group *")

                    </div>

                    <div class="form-group">
                        <label><b>Any Message?:</b></label>
                        @Html.TextBoxFor(m => m.Message, new { @class = "form-control" })
                    </div>




                    <button type="submit" class="btn btn-success">Request</button>
                    
                    <button type="reset" class="btn btn-danger">Cancel</button>

                }
            </div>
        </div>
    </div>

</div>