BloodFinder/Controllers/EmailController.cs
using BloodFinder.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Net;
using System.Net.Mail;
using System.Web.Helpers;

namespace BloodFinder.Controllers
{
    public class EmailController : Controller
    {
        // GET: Email
        public ActionResult Email()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Email(EmailModel obj)
        {
           
            try
            {
                
                WebMail.SmtpServer = "smtp.gmail.com";   
                WebMail.SmtpPort = 587;
                WebMail.SmtpUseDefaultCredentials = true;  
                WebMail.EnableSsl = true;
                WebMail.UserName =  "narenkarn786@gmail.com";
                WebMail.Password ="786naren";

                WebMail.From = "narenkarn786@gmail.com";

                WebMail.Send(to: obj.ToEmail, subject: obj.EmailSubject, body: obj.EMailBody, cc: obj.EmailCC, bcc: obj.EmailBCC, isBodyHtml: true);
              
                ViewBag.Status = "Email Sent Successfully.";
            }
            catch (Exception)
            {
                
                ViewBag.Status = "Problem while sending email, Please check details.";

            }
            return View();
        }

        
    }
}

BloodFinder/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BloodFinder.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


     
    }
}

BloodFinder/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<br /><br />
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-1">
            <img src="~/Photos/logo.png" alt="logo" height="100" width="100" />
        </div>
        <div class="col-lg-11">
            <center>
                <h1><b><u>About Us</u></b></h1>
            </center>
            <img src="~/Photos/270764.jpg" alt="Blood Donation" height="500" width="1000" />
        </div>
    </div>
    </div>
<br />
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-4">
                <h2><b><u>Our Purpose</u></b></h2>
                <p style="text-align:justify">
                    Universally, 'Blood' is recognized as the most precious element that sustains life. It saves innumerable lives across the world in a variety of conditions. Once in every 2- seconds, someone, somewhere is desperately in need of blood. More than 29 million units of blood components are transfused every year. The need for blood is great - on any given day, approximately 39,000 units of Red Blood Cells are needed. Each year, we could meet only up to 1% (approx) of our nation’s demand for blood transfusion.

                    Despite the increase in the number of donors, blood remains in short supply during emergencies, mainly attributed to the lack of information and accessibility. We positively believe this tool can overcome most of these challenges by effectively connecting the blood donors with the blood recipients.

                </p>
            </div>
            <div class="col-lg-4">
                <h2><b><u>Why Blood Finder?</u></b></h2>
            </div>

            <div class="col-lg-4">
                <h2><b><u>Why Blood Donation? </u></b></h2>
                <p style="text-align:justify">
                    Blood is the most precious gift that anyone can give to another person — the gift of life. A decision to donate your blood can save a life, or even several if your blood is separated into its components — red cells, platelets and plasma — which can be used individually for patients with specific conditions.Better health is enjoyed by those who donate their time, expertise or money to others who are in need. Charitable people tend to be able to cope with their own problems more easily than those who don't donate. Giving to others improves your self-esteem, self confidence and self worthBetter health is enjoyed by those who donate their time, expertise or money to others who are in need. Charitable people tend to be able to cope with their own problems more easily than those who don't donate. Giving to others improves your self-esteem, self confidence and self worth
                </p>
            </div>
        </div>
    </div>

BloodFinder/Views/Home/Contact.cshtml
@{


    ViewBag.Title = "Contact";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<br />

<script src='https://kit.fontawesome.com/a076d05399.js'></script>



<br />
<div class="container-fluid">
    <div class="row">

        <div class="cols-lg-4">
            <img src="~/Photos/logo.png" alt="logo" height="110" width="120" />
        </div>
        &nbsp;&nbsp;&nbsp;&nbsp;
        <div class="col-lg-8">
            <h1><b><u>Contact Us</u></b></h1>

            <h4> <i class="fas fa-phone-square-alt" style='font-size:25px'>&nbsp; </i> <b>Mobile No:</b> 9811399249</h4>
            <h4><i class="fas fa-envelope" style='font-size:25px'>&nbsp; </i> <b>E-Mail:</b>
            @Html.ActionLink("Blood Finder Nepal","Email","Email")</h4>


            <h4><b><u>Follow Us On:</u></b></h4><i class="fab fa-facebook-square" style='font-size:40px'></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fab fa-instagram" style='font-size:40px'></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<i class="fab fa-linkedin" style='font-size:40px'></i>

        </div>
    </div>
</div>

BloodFinder/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

<br />
<div >
    <div class="row">
        <div class="col-lg-1">
            <img src="~/Photos/logo.png" alt="logo" height="100" width="95" />

        </div>
        <div class="col-lg-11">
      
            <div id="demo" class="carousel slide" data-ride="carousel" data-interval="2000">

                <!-- Indicators -->
                <ul class="carousel-indicators">
                    <li data-target="#demo" data-slide-to="0" class="active"></li>
                    <li data-target="#demo" data-slide-to="1"></li>
                    <li data-target="#demo" data-slide-to="2"></li>
                    <li data-target="#demo" data-slide-to="3"></li>
                    <li data-target="#demo" data-slide-to="4"></li>
                </ul>

                <!-- The slideshow -->
                <div class="carousel-inner" >
                    <div class="carousel-item active" >
                        <img src="~/Photos/1029.jpg" height="600" width="1100">
                    </div>

                    <div class="carousel-item">
                        <img src="~/Photos/270764.jpg" height="600" width="1100">
                    </div>
                    <div class="carousel-item">
                        <img src="~/Photos/19257.jpg" height="600" width="1100">
                    </div>
                    <div class="carousel-item">
                        <img src="~/Photos/273641.png" height="600" width="1100">
                    </div>
                    <div class="carousel-item">
                        <img src="~/Photos/Edited1.jpg" height="600" width="1100">
                    </div>
                </div>

                <!-- Left and right controls -->
                <a class="carousel-control-prev" href="#demo" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </a>
                <a class="carousel-control-next" href="#demo" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </a>
            </div>

        </div>
    </div>
</div>